name: Push demo
on:
  push:

jobs:
  Next:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build A
        run: docker build -t a:latest --build-context shared=./context-shared/ ./context-a
      - name: Build B
        run: docker build -t b:latest --build-context shared=./context-shared/ ./context-b

      - name: Output A1
        run: docker run a:latest cat /one
      - name: Output B1
        run: docker run b:latest cat /one
      - name: Output B2
        run: docker run b:latest cat /two
